services:
  - type: web
    name: crudapi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000


